#############################################################################
# Makefile for building: GPURendering
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  GPURendering.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile GPURendering.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = GPURendering1.0.0
DISTDIR = /home/jordi/Escritorio/Universitat/GVD/ProjectesQt/p2-gpurendering-f02/.tmp/GPURendering1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = DataSettings/InfoMapping.cpp \
		DataSettings/PropertyInfo.cpp \
		DataSettings/Serializable.cpp \
		Factories/AbstractFactoryScenes.cpp \
		Factories/Builder.cpp \
		Factories/SceneFactory.cpp \
		Factories/SceneFactoryData.cpp \
		Factories/SceneFactoryVirtual.cpp \
		Modelling/Animation.cpp \
		Modelling/Lights/Light.cpp \
		Modelling/Materials/ColorMapStatic.cpp \
		Modelling/Materials/Material.cpp \
		Modelling/Objects/Cara.cpp \
		Modelling/Objects/Mesh.cpp \
		Modelling/Objects/Plane.cpp \
		Modelling/Scene.cpp \
		Modelling/TG/ScaleTG.cpp \
		Modelling/TG/TG.cpp \
		Modelling/TG/TranslateTG.cpp \
		Rendering/Camera.cpp \
		Rendering/GLWidget.cpp \
		library/Common.cpp \
		Main.cpp \
		Rendering/MainWindow.cpp qrc_resources.cpp \
		moc_Builder.cpp \
		moc_Mesh.cpp \
		moc_GLWidget.cpp \
		moc_MainWindow.cpp
OBJECTS       = InfoMapping.o \
		PropertyInfo.o \
		Serializable.o \
		AbstractFactoryScenes.o \
		Builder.o \
		SceneFactory.o \
		SceneFactoryData.o \
		SceneFactoryVirtual.o \
		Animation.o \
		Light.o \
		ColorMapStatic.o \
		Material.o \
		Cara.o \
		Mesh.o \
		Plane.o \
		Scene.o \
		ScaleTG.o \
		TG.o \
		TranslateTG.o \
		Camera.o \
		GLWidget.o \
		Common.o \
		Main.o \
		MainWindow.o \
		qrc_resources.o \
		moc_Builder.o \
		moc_Mesh.o \
		moc_GLWidget.o \
		moc_MainWindow.o
DIST          = LICENSE \
		README.md \
		libWin32/glut.dll \
		libWin32/glut.lib \
		libWin32/glut32.dll \
		libWin32/glut32.lib \
		resources/README.fst \
		resources/fshader1.glsl \
		resources/models/common-cockle.mtl \
		resources/models/cruiser.mtl \
		resources/models/f16.mtl \
		resources/models/sphere0.mtl \
		resources/models/sphere1.mtl \
		resources/textures/2k_earth_clouds.jpg \
		resources/textures/2k_earth_daymap.jpg \
		resources/textures/2k_earth_nightmap.jpg \
		resources/textures/2k_earth_normal_map.tif \
		resources/textures/2k_earth_specular_map.tif \
		resources/textures/2k_jupiter.jpg \
		resources/textures/2k_mars.jpg \
		resources/textures/2k_mercury.jpg \
		resources/textures/2k_moon.jpg \
		resources/textures/2k_saturn.jpg \
		resources/textures/2k_stars+milky_way.jpg \
		resources/textures/2k_sun.jpg \
		resources/textures/2k_uranus.jpg \
		resources/textures/2k_venus_atmosphere.jpg \
		resources/textures/2k_venus_surface.jpg \
		resources/textures/bricks.png \
		resources/textures/earth1.png \
		resources/textures/earth3.png \
		resources/textures/ennis.png \
		resources/textures/grace-new.png \
		resources/textures/metal_crosshatch_pattern_6190173.JPG \
		resources/vshader1.glsl \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GPURendering.pro ../p2-gpurendering-f02 \
		(1)/Factories/SceneFactoryData.h \
		DataSettings/InfoMapping.h \
		DataSettings/PropertyInfo.h \
		DataSettings/Serializable.h \
		Factories/AbstractFactoryScenes.h \
		Factories/Builder.h \
		Factories/SceneFactory.h \
		Factories/SceneFactoryData.h \
		Factories/SceneFactoryVirtual.h \
		IncludeWin32/GL/glut.h \
		Modelling/Animation.h \
		Modelling/Lights/Light.h \
		Modelling/Materials/ColorMap.h \
		Modelling/Materials/ColorMapStatic.h \
		Modelling/Materials/Material.h \
		Modelling/Objects/Cara.h \
		Modelling/Objects/Mesh.h \
		Modelling/Objects/Plane.h \
		Modelling/Scene.h \
		Modelling/TG/ScaleTG.h \
		Modelling/TG/TG.h \
		Modelling/TG/TranslateTG.h \
		Rendering/Camera.h \
		Rendering/GLWidget.h \
		library/Common.h \
		library/mat.h \
		library/vec.h \
		Rendering/MainWindow.h DataSettings/InfoMapping.cpp \
		DataSettings/PropertyInfo.cpp \
		DataSettings/Serializable.cpp \
		Factories/AbstractFactoryScenes.cpp \
		Factories/Builder.cpp \
		Factories/SceneFactory.cpp \
		Factories/SceneFactoryData.cpp \
		Factories/SceneFactoryVirtual.cpp \
		Modelling/Animation.cpp \
		Modelling/Lights/Light.cpp \
		Modelling/Materials/ColorMapStatic.cpp \
		Modelling/Materials/Material.cpp \
		Modelling/Objects/Cara.cpp \
		Modelling/Objects/Mesh.cpp \
		Modelling/Objects/Plane.cpp \
		Modelling/Scene.cpp \
		Modelling/TG/ScaleTG.cpp \
		Modelling/TG/TG.cpp \
		Modelling/TG/TranslateTG.cpp \
		Rendering/Camera.cpp \
		Rendering/GLWidget.cpp \
		library/Common.cpp \
		Main.cpp \
		Rendering/MainWindow.cpp
QMAKE_TARGET  = GPURendering
DESTDIR       = 
TARGET        = GPURendering


first: all
####### Build rules

GPURendering: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: GPURendering.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		GPURendering.pro \
		resources.qrc
	$(QMAKE) -o Makefile GPURendering.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_Baloo.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KI18n.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KService.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
GPURendering.pro:
resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile GPURendering.pro

qmake_all: FORCE


all: Makefile GPURendering

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../p2-gpurendering-f02 (1)/Factories/SceneFactoryData.h DataSettings/InfoMapping.h DataSettings/PropertyInfo.h DataSettings/Serializable.h Factories/AbstractFactoryScenes.h Factories/Builder.h Factories/SceneFactory.h Factories/SceneFactoryData.h Factories/SceneFactoryVirtual.h IncludeWin32/GL/glut.h Modelling/Animation.h Modelling/Lights/Light.h Modelling/Materials/ColorMap.h Modelling/Materials/ColorMapStatic.h Modelling/Materials/Material.h Modelling/Objects/Cara.h Modelling/Objects/Mesh.h Modelling/Objects/Plane.h Modelling/Scene.h Modelling/TG/ScaleTG.h Modelling/TG/TG.h Modelling/TG/TranslateTG.h Rendering/Camera.h Rendering/GLWidget.h library/Common.h library/mat.h library/vec.h Rendering/MainWindow.h $(DISTDIR)/
	$(COPY_FILE) --parents DataSettings/InfoMapping.cpp DataSettings/PropertyInfo.cpp DataSettings/Serializable.cpp Factories/AbstractFactoryScenes.cpp Factories/Builder.cpp Factories/SceneFactory.cpp Factories/SceneFactoryData.cpp Factories/SceneFactoryVirtual.cpp Modelling/Animation.cpp Modelling/Lights/Light.cpp Modelling/Materials/ColorMapStatic.cpp Modelling/Materials/Material.cpp Modelling/Objects/Cara.cpp Modelling/Objects/Mesh.cpp Modelling/Objects/Plane.cpp Modelling/Scene.cpp Modelling/TG/ScaleTG.cpp Modelling/TG/TG.cpp Modelling/TG/TranslateTG.cpp Rendering/Camera.cpp Rendering/GLWidget.cpp library/Common.cpp Main.cpp Rendering/MainWindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/qt5/bin/rcc \
		resources/fshader1.glsl \
		resources/vshaderDepthShading.glsl \
		resources/vshaderToon.glsl \
		resources/teapot2.obj \
		resources/f16.obj \
		resources/cube.obj \
		resources/fshaderDepthShading.glsl \
		resources/vshaderPhong.glsl \
		resources/fshaderGouraud.glsl \
		resources/meshExample.json \
		resources/fshaderPhong.glsl \
		resources/vshaderGouraud.glsl \
		resources/vshader1.glsl \
		resources/fshaderToon.glsl
	/usr/lib/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_Builder.cpp moc_Mesh.cpp moc_GLWidget.cpp moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Builder.cpp moc_Mesh.cpp moc_GLWidget.cpp moc_MainWindow.cpp
moc_Builder.cpp: Factories/Builder.h \
		Rendering/GLWidget.h \
		Rendering/Camera.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/Scene.h \
		Modelling/TG/TranslateTG.h \
		Modelling/TG/TG.h \
		Modelling/TG/ScaleTG.h \
		Modelling/Objects/Mesh.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h \
		DataSettings/Serializable.h \
		Modelling/Lights/Light.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jordi/Escritorio/Universitat/GVD/ProjectesQt/p2-gpurendering-f02/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jordi/Escritorio/Universitat/GVD/ProjectesQt/p2-gpurendering-f02 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Factories/Builder.h -o moc_Builder.cpp

moc_Mesh.cpp: Modelling/Objects/Mesh.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/TG/TG.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h \
		DataSettings/Serializable.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jordi/Escritorio/Universitat/GVD/ProjectesQt/p2-gpurendering-f02/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jordi/Escritorio/Universitat/GVD/ProjectesQt/p2-gpurendering-f02 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Modelling/Objects/Mesh.h -o moc_Mesh.cpp

moc_GLWidget.cpp: Rendering/GLWidget.h \
		Rendering/Camera.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/Scene.h \
		Modelling/TG/TranslateTG.h \
		Modelling/TG/TG.h \
		Modelling/TG/ScaleTG.h \
		Modelling/Objects/Mesh.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h \
		DataSettings/Serializable.h \
		Modelling/Lights/Light.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jordi/Escritorio/Universitat/GVD/ProjectesQt/p2-gpurendering-f02/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jordi/Escritorio/Universitat/GVD/ProjectesQt/p2-gpurendering-f02 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Rendering/GLWidget.h -o moc_GLWidget.cpp

moc_MainWindow.cpp: Rendering/MainWindow.h \
		Rendering/GLWidget.h \
		Rendering/Camera.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/Scene.h \
		Modelling/TG/TranslateTG.h \
		Modelling/TG/TG.h \
		Modelling/TG/ScaleTG.h \
		Modelling/Objects/Mesh.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h \
		DataSettings/Serializable.h \
		Modelling/Lights/Light.h \
		Factories/Builder.h \
		ui_mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/jordi/Escritorio/Universitat/GVD/ProjectesQt/p2-gpurendering-f02/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/jordi/Escritorio/Universitat/GVD/ProjectesQt/p2-gpurendering-f02 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtOpenGL -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Rendering/MainWindow.h -o moc_MainWindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

InfoMapping.o: DataSettings/InfoMapping.cpp DataSettings/InfoMapping.h \
		Modelling/Scene.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/TG/TranslateTG.h \
		Modelling/TG/TG.h \
		Modelling/TG/ScaleTG.h \
		Modelling/Objects/Mesh.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h \
		DataSettings/Serializable.h \
		Modelling/Lights/Light.h \
		Rendering/Camera.h \
		Modelling/Materials/ColorMapStatic.h \
		Modelling/Materials/ColorMap.h \
		DataSettings/PropertyInfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InfoMapping.o DataSettings/InfoMapping.cpp

PropertyInfo.o: DataSettings/PropertyInfo.cpp DataSettings/PropertyInfo.h \
		DataSettings/Serializable.h \
		Modelling/Materials/ColorMapStatic.h \
		Modelling/Materials/ColorMap.h \
		library/vec.h \
		Modelling/Objects/Mesh.h \
		library/Common.h \
		library/mat.h \
		Modelling/TG/TG.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PropertyInfo.o DataSettings/PropertyInfo.cpp

Serializable.o: DataSettings/Serializable.cpp DataSettings/Serializable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Serializable.o DataSettings/Serializable.cpp

AbstractFactoryScenes.o: Factories/AbstractFactoryScenes.cpp Factories/AbstractFactoryScenes.h \
		Factories/SceneFactory.h \
		DataSettings/Serializable.h \
		Modelling/Scene.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/TG/TranslateTG.h \
		Modelling/TG/TG.h \
		Modelling/TG/ScaleTG.h \
		Modelling/Objects/Mesh.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h \
		Modelling/Lights/Light.h \
		Rendering/Camera.h \
		Factories/SceneFactoryVirtual.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AbstractFactoryScenes.o Factories/AbstractFactoryScenes.cpp

Builder.o: Factories/Builder.cpp Factories/Builder.h \
		Rendering/GLWidget.h \
		Rendering/Camera.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/Scene.h \
		Modelling/TG/TranslateTG.h \
		Modelling/TG/TG.h \
		Modelling/TG/ScaleTG.h \
		Modelling/Objects/Mesh.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h \
		DataSettings/Serializable.h \
		Modelling/Lights/Light.h \
		Factories/AbstractFactoryScenes.h \
		Factories/SceneFactory.h \
		Factories/SceneFactoryVirtual.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Builder.o Factories/Builder.cpp

SceneFactory.o: Factories/SceneFactory.cpp Factories/SceneFactory.h \
		DataSettings/Serializable.h \
		Modelling/Scene.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/TG/TranslateTG.h \
		Modelling/TG/TG.h \
		Modelling/TG/ScaleTG.h \
		Modelling/Objects/Mesh.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h \
		Modelling/Lights/Light.h \
		Rendering/Camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SceneFactory.o Factories/SceneFactory.cpp

SceneFactoryData.o: Factories/SceneFactoryData.cpp Factories/SceneFactoryData.h \
		Modelling/Materials/ColorMapStatic.h \
		Modelling/Materials/ColorMap.h \
		library/vec.h \
		Modelling/Materials/Material.h \
		library/Common.h \
		library/mat.h \
		DataSettings/Serializable.h \
		Factories/SceneFactory.h \
		Modelling/Scene.h \
		Modelling/TG/TranslateTG.h \
		Modelling/TG/TG.h \
		Modelling/TG/ScaleTG.h \
		Modelling/Objects/Mesh.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Lights/Light.h \
		Rendering/Camera.h \
		DataSettings/InfoMapping.h \
		DataSettings/PropertyInfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SceneFactoryData.o Factories/SceneFactoryData.cpp

SceneFactoryVirtual.o: Factories/SceneFactoryVirtual.cpp Factories/SceneFactoryVirtual.h \
		Factories/SceneFactory.h \
		DataSettings/Serializable.h \
		Modelling/Scene.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/TG/TranslateTG.h \
		Modelling/TG/TG.h \
		Modelling/TG/ScaleTG.h \
		Modelling/Objects/Mesh.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h \
		Modelling/Lights/Light.h \
		Rendering/Camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SceneFactoryVirtual.o Factories/SceneFactoryVirtual.cpp

Animation.o: Modelling/Animation.cpp Modelling/Animation.h \
		Modelling/TG/TG.h \
		library/Common.h \
		library/vec.h \
		library/mat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Animation.o Modelling/Animation.cpp

Light.o: Modelling/Lights/Light.cpp Modelling/Lights/Light.h \
		library/vec.h \
		library/Common.h \
		library/mat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Light.o Modelling/Lights/Light.cpp

ColorMapStatic.o: Modelling/Materials/ColorMapStatic.cpp Modelling/Materials/ColorMapStatic.h \
		Modelling/Materials/ColorMap.h \
		library/vec.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ColorMapStatic.o Modelling/Materials/ColorMapStatic.cpp

Material.o: Modelling/Materials/Material.cpp Modelling/Materials/Material.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		DataSettings/Serializable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Material.o Modelling/Materials/Material.cpp

Cara.o: Modelling/Objects/Cara.cpp Modelling/Objects/Cara.h \
		library/vec.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cara.o Modelling/Objects/Cara.cpp

Mesh.o: Modelling/Objects/Mesh.cpp Modelling/Objects/Mesh.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/TG/TG.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h \
		DataSettings/Serializable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Mesh.o Modelling/Objects/Mesh.cpp

Plane.o: Modelling/Objects/Plane.cpp Modelling/Objects/Plane.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/Materials/Material.h \
		DataSettings/Serializable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Plane.o Modelling/Objects/Plane.cpp

Scene.o: Modelling/Scene.cpp Modelling/Scene.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/TG/TranslateTG.h \
		Modelling/TG/TG.h \
		Modelling/TG/ScaleTG.h \
		Modelling/Objects/Mesh.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h \
		DataSettings/Serializable.h \
		Modelling/Lights/Light.h \
		Rendering/Camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scene.o Modelling/Scene.cpp

ScaleTG.o: Modelling/TG/ScaleTG.cpp Modelling/TG/ScaleTG.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/TG/TG.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScaleTG.o Modelling/TG/ScaleTG.cpp

TG.o: Modelling/TG/TG.cpp Modelling/TG/TG.h \
		library/Common.h \
		library/vec.h \
		library/mat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TG.o Modelling/TG/TG.cpp

TranslateTG.o: Modelling/TG/TranslateTG.cpp Modelling/TG/TranslateTG.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/TG/TG.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TranslateTG.o Modelling/TG/TranslateTG.cpp

Camera.o: Rendering/Camera.cpp Rendering/Camera.h \
		library/Common.h \
		library/vec.h \
		library/mat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Camera.o Rendering/Camera.cpp

GLWidget.o: Rendering/GLWidget.cpp Rendering/GLWidget.h \
		Rendering/Camera.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/Scene.h \
		Modelling/TG/TranslateTG.h \
		Modelling/TG/TG.h \
		Modelling/TG/ScaleTG.h \
		Modelling/Objects/Mesh.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h \
		DataSettings/Serializable.h \
		Modelling/Lights/Light.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLWidget.o Rendering/GLWidget.cpp

Common.o: library/Common.cpp library/Common.h \
		library/vec.h \
		library/mat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Common.o library/Common.cpp

Main.o: Main.cpp Rendering/MainWindow.h \
		Rendering/GLWidget.h \
		Rendering/Camera.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/Scene.h \
		Modelling/TG/TranslateTG.h \
		Modelling/TG/TG.h \
		Modelling/TG/ScaleTG.h \
		Modelling/Objects/Mesh.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h \
		DataSettings/Serializable.h \
		Modelling/Lights/Light.h \
		Factories/Builder.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Main.cpp

MainWindow.o: Rendering/MainWindow.cpp Rendering/MainWindow.h \
		Rendering/GLWidget.h \
		Rendering/Camera.h \
		library/Common.h \
		library/vec.h \
		library/mat.h \
		Modelling/Scene.h \
		Modelling/TG/TranslateTG.h \
		Modelling/TG/TG.h \
		Modelling/TG/ScaleTG.h \
		Modelling/Objects/Mesh.h \
		Modelling/Animation.h \
		Modelling/Objects/Cara.h \
		Modelling/Materials/Material.h \
		DataSettings/Serializable.h \
		Modelling/Lights/Light.h \
		Factories/Builder.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o Rendering/MainWindow.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_Builder.o: moc_Builder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Builder.o moc_Builder.cpp

moc_Mesh.o: moc_Mesh.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Mesh.o moc_Mesh.cpp

moc_GLWidget.o: moc_GLWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GLWidget.o moc_GLWidget.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/GPURendering/bin || mkdir -p $(INSTALL_ROOT)/opt/GPURendering/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/GPURendering/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/GPURendering/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/GPURendering/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/GPURendering/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

